name: Push to Public Repo

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy-to-public:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_76981 }}
        with:
          source-directory: 'zad1_cv'
          destination-github-username: '76981ArtemHromliuk'
          destination-repository-name: 'cv-link76981'
          user-email: ahromli1@stu.vistula.edu.pl
          user-name: github-actions
          target-branch: main
